backend/modules/wechat/controllers/ReplyDefaultController.php
<?php

namespace backend\modules\wechat\controllers;

use Yii;
use common\helpers\ArrayHelper;
use common\models\wechat\ReplyDefault;
use backend\controllers\BaseController;

/**
 * 默认回复控制器
 *
 * Class ReplyDefaultController
 * @package backend\modules\wechat\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class ReplyDefaultController extends BaseController
{
    /**
     * 首页
     *
     * @return mixed|string
     */
    public function actionIndex()
    {
        $model = $this->findModel();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->message('修改成功', $this->redirect(['index']));
        }

        // 关键字
        $keyword = Yii::$app->services->wechatRuleKeyword->getList();
        $keyword = ArrayHelper::map($keyword, 'content', 'content');
        $keyword = ArrayHelper::merge([' ' => '不触发关键字'], $keyword);

        return $this->render('index', [
            'model' => $model,
            'keyword' => $keyword
        ]);
    }

    /**
     * 返回模型
     *
     * @return array|ReplyDefault|null|yii\db\ActiveRecord
     */
    protected function findModel()
    {
        if (empty(($model = ReplyDefault::find()->filterWhere(['merchant_id' => $this->getMerchantId()])->one()))) {
            return new ReplyDefault;
        }

        return $model;
    }
}

backend/modules/wechat/controllers/RuleController.php
<?php

namespace backend\modules\wechat\controllers;

use Yii;
use yii\data\Pagination;
use yii\helpers\Json;
use common\enums\StatusEnum;
use common\models\wechat\Rule;
use common\models\wechat\RuleKeyword;
use common\components\Curd;
use backend\modules\wechat\forms\RuleForm;
use backend\controllers\BaseController;

/**
 * Class RuleController
 * @package backend\modules\wechat\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class RuleController extends BaseController
{
    use Curd;

    /**
     * @var Rule
     */
    public $modelClass = Rule::class;

    /**
     * @return string
     */
    public function actionIndex()
    {
        $request = Yii::$app->request;
        $module = $request->get('module', null);
        $keyword = $request->get('keyword', null);

        $data = Rule::find()
            ->where(['>=', 'status', StatusEnum::DISABLED])
            ->andWhere(['in', 'module', array_keys(Rule::$moduleExplain)])
            ->andFilterWhere(['module' => $module])
            ->andFilterWhere(['merchant_id' => $this->getMerchantId()])
            ->andFilterWhere(['like', 'name', $keyword]);

        $pages = new Pagination(['totalCount' => $data->count(), 'pageSize' => $this->pageSize]);
        $models = $data->offset($pages->offset)
            ->orderBy('sort asc,created_at desc')
            ->with('ruleKeyword')
            ->limit($pages->limit)
            ->all();

        return $this->render($this->action->id, [
            'models' => $models,
            'pages' => $pages,
            'modules' => Rule::$moduleExplain,
            'module' => $module,
            'keyword' => $keyword,
        ]);
    }

    /**
     * @return mixed|string|\yii\web\Response
     * @throws \yii\base\ExitException
     */
    public function actionEdit()
    {
        $request = Yii::$app->request;
        $id = $request->get('id');
        $model = $this->findModel($id);
        $defaultRuleKeywords = Yii::$app->services->wechatRuleKeyword->getType($model->ruleKeyword);
        $postData = Yii::$app->request->post();

        $this->activeFormValidate($model);
        if ($model->load($postData)) {
            $transaction = Yii::$app->db->beginTransaction();

            try {
                if (!$model->save()) {
                    throw new \Exception($this->getError($model));
                }

                // 全部关键字
                $ruleKey = $postData['ruleKey'] ?? [];
                $ruleKey[RuleKeyword::TYPE_MATCH] = explode(',', $model->keyword);
                // 更新关键字
                Yii::$app->services->wechatRuleKeyword->update($model, $ruleKey, $defaultRuleKeywords);
                $transaction->commit();

                return $this->redirect(['index', 'module' => $model->module]);
            } catch (\Exception $e) {
                $transaction->rollBack();
                return $this->message($e->getMessage(), $this->redirect(['index']), 'error');
            }
        }

        return $this->render($this->action->id, [
            'model' => $model,
            'ruleKeywords' => $defaultRuleKeywords,
            'modules' => Json::encode(Rule::$moduleExplain),
            'apiList' => Yii::$app->services->wechatRule->getApiList(),
        ]);
    }

    /**
     * 返回模型
     *
     * @param $id
     * @return mixed
     */
    protected function findModel($id)
    {
        if (empty($id) || empty(($model = RuleForm::find()->where(['id' => $id])->andFilterWhere(['merchant_id' => $this->getMerchantId()])->one()))) {
            $model = new RuleForm();
            return $model->loadDefaultValues();
        }

        return $model;
    }
}

backend/modules/wechat/controllers/SettingController.php
<?php

namespace backend\modules\wechat\controllers;

use Yii;
use backend\controllers\BaseController;
use backend\modules\wechat\forms\HistoryForm;

/**
 * 微信参数设置
 *
 * Class SettingController
 * @package backend\modules\wechat\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class SettingController extends BaseController
{
    /**
     * @return mixed|string
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionHistoryStat()
    {
        $model = new HistoryForm();
        $model->attributes = Yii::$app->services->wechatSetting->getByFieldName('history');
        if (Yii::$app->request->isPost && $model->validate()) {
            try {
                Yii::$app->services->wechatSetting->setByFieldName('history', Yii::$app->request->post('HistoryForm'));
                return $this->message('修改成功', $this->redirect(['history-stat']));
            } catch (\Exception $e) {
                return $this->message($e->getMessage(), $this->redirect(['history-stat']), 'error');
            }
        }

        return $this->render('history-stat', [
            'model' => $model,
        ]);
    }

    /**
     * @return mixed|string
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionSpecialMessage()
    {
        if (Yii::$app->request->isPost) {
            try {
                Yii::$app->services->wechatSetting->setByFieldName('special', Yii::$app->request->post('setting'));
                return $this->message('修改成功', $this->redirect(['special-message']));
            } catch (\Exception $e) {
                return $this->message($e->getMessage(), $this->redirect(['special-message']), 'error');
            }
        }

        return $this->render('special-message', [
            'list' => Yii::$app->services->wechatSetting->specialConfig(),
        ]);
    }
}

backend/modules/wechat/views/reply-default/index.php
<?php
use common\helpers\Url;
use yii\widgets\ActiveForm;

$this->title = '关注/默认回复';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-sm-12">
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <li><a href="<?= Url::to(['rule/index'])?>"> 关键字自动回复</a></li>
                <li><a href="<?= Url::to(['setting/special-message'])?>"> 非文字自动回复</a></li>
                <li class="active"><a href="<?= Url::to(['reply-default/index'])?>"> 关注/默认回复</a></li>
            </ul>
            <div class="tab-content">
                <div class="active tab-pane rf-auto">
                    <?php $form = ActiveForm::begin(); ?>
                    <div class="col-sm-12">
                        <?= $form->field($model, 'follow_content')->widget(\kartik\select2\Select2::class, [
                            'data' => $keyword,
                            'options' => ['placeholder' => '请选择'],
                            'pluginOptions' => [
                                'allowClear' => false,
                                'tags' => true,
                            ],
                        ])->hint('注意：这里是自动回复设置的关键字，设置用户添加公众帐号好友时，发送的欢迎信息。');?>

                        <?= $form->field($model, 'default_content')->widget(\kartik\select2\Select2::class, [
                            'data' => $keyword,
                            'options' => ['placeholder' => '请选择'],
                            'pluginOptions' => [
                                'allowClear' => true,
                                'tags' => true,
                            ],
                        ])->hint('注意：这里是自动回复设置的关键字，当系统不知道该如何回复粉丝的消息时，默认发送的内容。');?>
                    </div>
                    <div class="col-sm-12 text-center">
                        <button class="btn btn-primary" type="submit">保存</button>
                    </div>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
    </div>
</div>